migrate((app) => {
    // up
    // Create Webhooks collection
    const collection = new Collection({
        // id autogenerated
        name: "webhook",
        type: "base",
        listRule: null, // null = admin only
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        schema: [
            {
                name: "name",
                type: "text",
                required: true,
                options: {
                    max: 100,
                },
            },
            {
                name: "url",
                type: "text",
                required: true,
            },
            {
                name: "collection",
                type: "text",
                required: true,
            },
            {
                name: "trigger",
                type: "text",
                required: true,
            },
            {
                name: "request_method",
                type: "text",
                required: true,
            },
            {
                name: "request_body",
                type: "text",
                required: true,
            },
        ],
        indexes: [
        ],
        options: {}
    })
    app.save(collection);
}, (app) => {
    // down
    try {
        const collection = app.findCollectionByNameOrId("webhook")
        app.delete(collection)
    } catch (_) {
        /* most likely already gone */
    }
})